name: Release

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26
      - name: Build alignpkg
        run: go build alignpkg.go
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: Uploading alignpkg assets...
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: alignpkg*
